name: Docs-Generation

on:   
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

permissions:
  pages: write
  deployments: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: run python
        run: python3 test.py
